### ISSUE TITLE
Examples provided in this repo are not getting synced

### ISSUE THREAD

**Issue by vdveldet** [coopnorge/provider-github#26]
I basically followed the examples in the repo here but my hello-provider-github is not getting in sync.

1. Installed provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-github
spec:
  package: xpkg.upbound.io/coopnorge/provider-github:v0.3.2
```
2.  Added the credentials and connection to github
```
---
apiVersion: v1
kind: Secret
metadata:
  name: provider-secret
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: "{\"token\":\"${GH_TOKEN}\",\"owner\":\"${GH_OWNER}\"}"

---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-secret
      namespace: crossplane-system
      key: credentials
```
3. Added the hello-provider-github repository
```
---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: hello-provider-github
spec:
  forProvider:
    visibility: public
    gitignoreTemplate: Terraform

    # securityAndAnalysis:
    #   - advancedSecurity:
    #     - status: enabled
    #     secretScanning:
    #     - status: disabled
    #     secretScanningPushProtection:
    #     - status: disabled  
  providerConfigRef:
    name: default

```

```
kubectl -n crossplane-system get Repository hello-provider-github
NAME                    READY   SYNCED   EXTERNAL-NAME           AGE
hello-provider-github           False    hello-provider-github   18m
```
```
kubectl -n crossplane-system describe Repository hello-provider-github
Name:         hello-provider-github
Namespace:    
Labels:       <none>
Annotations:  crossplane.io/external-name: hello-provider-github
API Version:  repo.github.upbound.io/v1alpha1
Kind:         Repository
Metadata:
  Creation Timestamp:  2023-05-12T06:42:05Z
  Generation:          1
  Managed Fields:
    API Version:  repo.github.upbound.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:deletionPolicy:
        f:forProvider:
          .:
          f:gitignoreTemplate:
          f:visibility:
        f:providerConfigRef:
          .:
          f:name:
    Manager:      kubectl
    Operation:    Update
    Time:         2023-05-12T06:42:05Z
    API Version:  repo.github.upbound.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:crossplane.io/external-name:
    Manager:      provider
    Operation:    Update
    Time:         2023-05-12T06:42:05Z
    API Version:  repo.github.upbound.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:atProvider:
        f:conditions:
    Manager:         provider
    Operation:       Update
    Subresource:     status
    Time:            2023-05-12T06:42:06Z
  Resource Version:  59230867
  UID:               709fc2cc-560a-4a84-93fe-2696d7a10eb5
Spec:
  Deletion Policy:  Delete
  For Provider:
    Gitignore Template:  Terraform
    Visibility:          public
  Provider Config Ref:
    Name:  default
Status:
  At Provider:
  Conditions:
    Last Transition Time:  2023-05-12T06:42:06Z
    Message:               observe failed: cannot run refresh: refresh failed: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
    Reason:  ReconcileError
    Status:  False
    Type:    Synced
Events:
  Type     Reason                         Age                From                                                      Message
  ----     ------                         ----               ----                                                      -------
  Warning  CannotObserveExternalResource  3s (x24 over 18m)  managed/repo.github.upbound.io/v1alpha1, kind=repository  cannot run refresh: refresh failed: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.

```
