### ISSUE TITLE
How to configure to create repo in an org?

### ISSUE THREAD

**Issue by patrickleet** [coopnorge/provider-github#27]
I can't seem to figure out how to create the repo in an org instead of the token owner's account.

Looks like it's a provider config option in TF: https://registry.terraform.io/providers/integrations/github/latest/docs#owner

**Comment by patrickleet** [comment]
`GITHUB_OWNER` can be passed in via a ControllerConfig

```yaml
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: crossplane-provider-github
spec:
  env:
  - name: GITHUB_OWNER
    value: the-org-name
    
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-github
spec:
  package: xpkg.upbound.io/coopnorge/provider-github:v0.3.2
  controllerConfigRef:
    name: crossplane-provider-github 
```
