### ISSUE TITLE
Cannot unmarshal string into Go value of type clients.githubConfig

### ISSUE THREAD

**Issue by KALAKATASUNEETHA** [coopnorge/provider-github#82]
Hi, I followed example of creating the secret for github app credentials

```

`apiVersion: v1
kind: Secret
metadata:
  name: provider-secret
  namespace: upbound-system
type: Opaque
stringData:
  credentials: "{\"app_auth\": [{\"id\": \"${APP_ID}\", \"installation_id\": \"${APP_INSTALLATION_ID}\", \"pem_file\": \"${APP_PEM_FILE}\"}] ,\"owner\":\"${GH_OWNER}\"}"
`
```

When I tried to create the repository resource , its failing with the following error 
`cannot get terraform setup: cannot unmarshal github credentials as JSON: json: cannot unmarshal string into Go value of type clients.githubConfig`
